# for class ManagerInformation
_manager:
    pattern:  /manager
    defaults: { _controller: ManagerMainBundle:PageManager:manager }

_allShopsManager:
    pattern:  /manager/allShops
    defaults: { _controller: ManagerMainBundle:PageManager:shops }

