# route for controller Main
_main:
    pattern:  /
    defaults: { _controller: PlatformMainBundle:Page:index }

_shops:
    pattern:  /shops
    defaults: { _controller: PlatformMainBundle:Page:shops }

_news:
    pattern: /news
    defaults: { _controller: PlatformMainBundle:Page:news }

#route for class ProductsPlatform
_productsPlatform:
    pattern:  /products
    defaults: { _controller: PlatformMainBundle:Products:all }

_productPlatform:
    pattern:  /product/{id}
    defaults: { _controller: PlatformMainBundle:Products:product }

# for class Search
_search:
    pattern:  /search
    defaults: { _controller: PlatformMainBundle:Search:search }

_resultProduct:
    pattern:  /resultProduct
    defaults: { _controller: PlatformMainBundle:Search:result }

# for class SearchMain
_resultProductPlatform:
    pattern:  /resultProductPlatform
    defaults: { _controller: PlatformMainBundle:SearchMain:result }