# route for controller Main
_main:
    pattern:  /
    defaults: { _controller: PlatformMainBundle:Page:index }

_shops:
    pattern:  /shops
    defaults: { _controller: PlatformMainBundle:Page:shops }

_productsPlatform:
    pattern:  /products
    defaults: { _controller: PlatformMainBundle:Page:products }

_productPlatform:
    pattern:  /products/{id}
    defaults: { _controller: PlatformMainBundle:Page:product }

_search:
    pattern:  /search
    defaults: { _controller: PlatformMainBundle:Page:search }

_news:
    pattern: /news
    defaults: { _controller: PlatformMainBundle:Page:news }

# for class Search
_paginationsShops:
    pattern:  /paginationsShops/{count}
    defaults: { _controller: PlatformMainBundle:Ajax:shops, _format: json }

_paginationsProducts:
    pattern:  /paginationsProducts/{count}
    defaults: { _controller: PlatformMainBundle:Ajax:products, _format: json }

_resultProducts:
    pattern:  /result
    defaults: { _controller: PlatformMainBundle:Ajax:result, _format: json }