# route for controller Main
_main:
    pattern:  /
    defaults: { _controller: PlatformMainBundle:Page:index }

_shops:
    pattern:  /shops
    defaults: { _controller: PlatformMainBundle:Page:shops }

_news:
    pattern: /news
    defaults: { _controller: PlatformMainBundle:Page:news }

#route for class ProductsPlatform
_productsPlatform:
    pattern:  /products
    defaults: { _controller: PlatformMainBundle:Products:all }

_productPlatform:
    pattern:  /product/{id}
    defaults: { _controller: PlatformMainBundle:Products:product }