parameters:
    countShopProductUser.class: Platform\MainBundle\Services\CountShopProductUser
    searchProduct.class: Platform\MainBundle\Services\SearchProduct

services:
    countShopProductUser:
        class: %countShopProductUser.class%
        arguments: [ @doctrine.orm.entity_manager ]

    searchProduct:
        class: %searchProduct.class%
        arguments: [ @doctrine.orm.entity_manager, @form.factory ]