# route for class Basket
_basket:
    pattern:  /basket
    defaults: { _controller: ShopOrderBundle:Basket:basket }
    
# for class Form add basket
_addProductBasket:
    pattern:  /addProductBasket
    defaults: { _controller: ShopOrderBundle:FormAddBasket:addProduct }
    
_deleteOrderUser:
    pattern:  /deleteOrderUser
    defaults: { _controller: ShopOrderBundle:FormAddBasket:delete }
   
# for class Delivery
_deliveryOrder:
    pattern:  /deivery/{orderNumber}
    defaults: { _controller: ShopOrderBundle:Delivery:form }
    
_saveDeliveryOrder:
    pattern:  /saveDeivery/{orderNumber}
    defaults: { _controller: ShopOrderBundle:Delivery:add }
    
# for class Payment
_payment_details:
    pattern:  /payment/{orderNumber}/details
    defaults: { _controller: ShopOrderBundle:Payment:details }
    
_payment_complete:
    pattern:  /payment/{orderNumber}/complete
    defaults: { _controller: ShopOrderBundle:Payment:complete }
    
_payment_cancel:
    pattern:  /payment/{orderNumber}/cancel
    defaults: { _controller: ShopOrderBundle:Payment:cancel }