#parameters:
#    allShopsUser.class: Manager\ShopsBundle\Services\AllShopsUser

#services:
#    allShopsUser:
#        class: %allShopsUser.class%
#       arguments: [ @doctrine.orm.entity_manager ]
