Shop\AddProductBundle\Entity\HashTags:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [tags]
        name:
            expose: true
            groups: [tags]