#routes for class Registration
_register:
    pattern:  /register
    defaults: { _controller: UserUserBundle:Auth:registration }

# route for class Main
_user:
    pattern:  /user
    defaults: { _controller: UserUserBundle:Main:user }
    
_userID:
    pattern:  /id/{id}
    defaults: { _controller: UserUserBundle:Main:userFriends }

_manager:
    pattern:  /manager
    defaults: { _controller: UserUserBundle:Main:manager }

_allShopsManager:
    pattern:  /manager/allShops
    defaults: { _controller: UserUserBundle:Main:shops }

# route for class Bookmarks
_subscribeShop:
    pattern: /subscribeShop
    defaults: { _controller: UserUserBundle:Bookmarks:subscribe }
    
_bookmarks:
    pattern: /user/bookmarks
    defaults: { _controller: UserUserBundle:Bookmarks:bookmarks }

# routes for class UserInformationController
_property:
    pattern:  /property
    defaults: { _controller: UserUserBundle:UserInformation:property }

_formInformation:
    pattern:  /property/information
    defaults: { _controller: UserUserBundle:UserInformation:formInformation }

_formPassword:
    pattern:  /property/password
    defaults: { _controller: UserUserBundle:UserInformation:formPassword }

_formPreviewInformation:
    pattern:  /property/formPreviewInformation
    defaults: { _controller: UserUserBundle:UserInformation:formPreview }

# route for class AjaxCity
_city:
    pattern:  /city/{id}
    defaults: { _controller: UserUserBundle:Ajax:city, _format: json }
    requirements:
        _method: GET

_emailProperty:
    pattern:  /emailProperty/{mail}
    defaults: { _controller: UserUserBundle:Ajax:email, _format: json }
    requirements:
        _method: GET

_checkEmail:
    pattern:  /checkEmail/{mail}
    defaults: { _controller: UserUserBundle:Ajax:checkEmail, _format: json }
    requirements:
        _method: GET

_descriptionUser:
    pattern:  /add/description
    defaults: { _controller: UserUserBundle:Ajax:description, _format: json }
    requirements:
        _method: POST

_uploadAvatar:
    pattern:  /avatar/upload
    defaults: { _controller: UserUserBundle:Ajax:upload, _format: json }
    requirements:
        _method: POST