parameters:
    
services:        
    shop.subscribe:
        class: User\UserBundle\Services\ShopSubscribe
        arguments: ["@doctrine.orm.entity_manager"]
        
    bookmarks:
        class: User\UserBundle\Services\Bookmarks
        arguments: ["@doctrine.orm.entity_manager"]

    change.password:
        class: User\UserBundle\Services\ChangePassword
        arguments: ["@doctrine.orm.entity_manager", "@form.factory", "@hash.password"]

    hash.password:
        class: User\UserBundle\Services\HashPassword

    hwi_oauth.user.provider.entity:
        class: HWI\Bundle\OAuthBundle\Security\Core\User\OAuthUserProvider

    ib_user.oauth_user_provider:
        class: User\UserBundle\Auth\OAuthProvider
        arguments: ["@doctrine", {vkontakte: vkontakte_id, facebook: facebook_id, google: google_id}]