# route for controller AjaxUnread
_allUnread:
    pattern:  /message/unread/all
    defaults: { _controller: UserMessagesBundle:AjaxUnread:all }
    
_inboxUnread:
    pattern:  /message/unread/inbox
    defaults: { _controller: UserMessagesBundle:AjaxUnread:inbox }
    
_outboxUnread:
    pattern:  /message/unread/outbox
    defaults: { _controller: UserMessagesBundle:AjaxUnread:outbox }
    
# route for controller Message
_allMessage:
    pattern:  /message
    defaults: { _controller: UserMessagesBundle:Message:all }
    
_inboxMessage:
    pattern:  /message/inbox
    defaults: { _controller: UserMessagesBundle:Message:inbox }
    
_outboxMessage:
    pattern:  /message/outbox
    defaults: { _controller: UserMessagesBundle:Message:outbox }
    
_deleteMessage:
    pattern:  /message/delete
    defaults: { _controller: UserMessagesBundle:Message:delete }

# route for controller AjaxDialog
_basketDialog:
    pattern:  /message/userMessage/basketDialog
    defaults: { _controller: UserMessagesBundle:AjaxDialog:basket }
    
_dialogDelete:
    pattern:  /message/userMessage/deleteDialog
    defaults: { _controller: UserMessagesBundle:AjaxDialog:delete }
    
# route for controller AjaxMessage
_allMessages:
    pattern:  /message/userMessage/allMessage
    defaults: { _controller: UserMessagesBundle:AjaxMessage:allMessage }
    
_basketMessage:
    pattern:  /message/userMessage/basketMessage
    defaults: { _controller: UserMessagesBundle:AjaxMessage:basketMessage }
    
_dialogCheck:
    pattern:  /message/userMessage/check
    defaults: { _controller: UserMessagesBundle:AjaxMessage:check }
    
_dialogCheckAll:
    pattern:  /message/userMessage/checkAll
    defaults: { _controller: UserMessagesBundle:AjaxMessage:checkAll }
    
_messageBasket:
    pattern:  /message/userMessage/basket
    defaults: { _controller: UserMessagesBundle:AjaxMessage:basket }
    
_messageDelete:
    pattern:  /message/userMessage/delete
    defaults: { _controller: UserMessagesBundle:AjaxMessage:delete }
    
# route for controller Dialog
_userDialog:
    pattern:  /message/userMessage/{id}/{users}
    defaults: { _controller: UserMessagesBundle:Dialog:message }
    
_addMessageDialog:
    pattern:  /message/addMessagePrivate
    defaults: { _controller: UserMessagesBundle:Dialog:add }
    
_returnMessage:
    pattern:  /message/returnMessage
    defaults: { _controller: UserMessagesBundle:Dialog:return }
   
# route for controller CreateDialog
_sendMessage:
    pattern:  /message/sendMessage/{id}
    defaults: { _controller: UserMessagesBundle:CreateDialog:form }
    
_addMessage:
    pattern:  /message/addMessage
    defaults: { _controller: UserMessagesBundle:CreateDialog:add }
