# route for SearchPartners
_searchUsers:
    pattern:  /friends/searchUsers
    defaults: { _controller: SearchUserBundle:SearchUsers:searchUsers }
    
_resualtSearchUser:
    pattern:  /friends/resualtSearch
    defaults: { _controller: SearchUserBundle:SearchUsers:resualtSearch }
