user_order:
    resource: "@UserOrderBundle/Resources/config/routing.yml"
    prefix:   /

user_messages:
    resource: "@UserMessagesBundle/Resources/config/routing.yml"
    prefix:   /

user_friends:
    resource: "@UserFriendsBundle/Resources/config/routing.yml"
    prefix:   /
    
user_user:
    resource: "@UserUserBundle/Controller/"
    prefix:   /

user_advertising:
    resource: "@UserAdvertisingBundle/Controller/"
    prefix:   /

shop_partners:
    resource: "@ShopPartnersBundle/Resources/config/routing.yml"
    prefix:   /

platform_main:
    resource: "@PlatformMainBundle/Controller/"
    type:   annotation
    
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
    
# my login form
login:
    path:   /login
    defaults:  { _controller: UserUserBundle:Auth:login }
    
login_check:
    path:   /login_check
    
logout:
    path:   /logout
    
# HWI
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect
    
hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect
    
vkontakte_login:
    path: /login/check-vkontakte
    
facebook_login:
    path: /login/check-facebook
    
google_login:
    path: /login/check-google

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /doc
    
# shop route
shop_order:
    resource: "@ShopOrderBundle/Controller/"
    prefix:   /
    
shop_product:
    resource: "@ShopProductBundle/Resources/config/routing.yml"
    prefix:   /

shop_information:
    resource: "@ShopInformationBundle/Controller/"
    prefix:   /

shop_create:
    resource: "@ShopCreateBundle/Controller/"
    prefix:   /