security:
    encoders:
        User\UserBundle\Entity\Users: sha512

    role_hierarchy:
        ROLE_ANONIM_USER: IS_AUTHENTICATED_FULLY
        ROLE_MANAGER:     [ROLE_USER]
        ROLE_ADMIN:       [ROLE_MANAGER]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        hwi_provider:
            id: ib_user.oauth_user_provider
        main:
            entity:
                class: User\UserBundle\Entity\Users
                property: username

    firewalls:            
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        main:
            pattern: ^/
            security: true
            form_login:
                provider: main
                login_path: login
                check_path: login
            logout:
                path:   /logout
                target: /
            anonymous: true
            remember_me:
                key:      "%secret%"
                lifetime: 604800 # 1 week in seconds
                path:     /
            
            oauth:
                resource_owners:
                    vkontakte: "/login/check-vkontakte"
                    instagram: "/login/check-instagram"
                login_path: /login
                failure_path: /login

                oauth_user_provider:
                    service: ib_user.oauth_user_provider

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user, roles: [ROLE_USER] }
        - { path: ^/id, roles: [ROLE_USER] }
        - { path: ^/property, roles: [ROLE_USER] }
        - { path: ^/firends, roles: [ROLE_USER] }
        - { path: ^/partners, roles: [ROLE_MANAGER] }
        - { path: ^/message, roles: [ROLE_USER] }
        - { path: ^/order, roles: [ROLE_USER] }
        - { path: ^/advertising, roles: [ROLE_MANAGER] }
        - { path: ^/addImageProduct, roles: [ROLE_MANAGER] }