# for class Products
_allProductsCategoryShop:
    pattern:  /{shopname}/allProduct/{idFloor}/{idCategory}
    defaults: { _controller: ShopProductBundle:Products:allProductsCategory }
    
_allProductsSubcategoryShop:
    pattern:  /{shopname}/allProduct/{idFloor}/{idCategory}/{idSubcategory}
    defaults: { _controller: ShopProductBundle:Products:allProductsSubcategory }
    
_productShop:
    pattern:  /{shopname}/allProduct/{idProduct}
    defaults: { _controller: ShopProductBundle:Products:product }

# route for controller Ajax
_addLikeProduct:
    pattern:  /addLikeProduct
    defaults: { _controller: ShopProductBundle:Ajax:like, _format: json }
    requirements:
        _method: GET

_hashTags:
    pattern:  /hashTags
    defaults: { _controller: ShopProductBundle:Ajax:hashTags, _format: json }
    requirements:
        _method: GET

# route for class Put
_addProduct:
    pattern:  /{shopname}/addProducts
    defaults: { _controller: ShopProductBundle:Put:add }

_updateProduct:
    pattern:  /{shopname}/updateProducts/{id}
    defaults: { _controller: ShopProductBundle:Put:update }
