# for class AjaxCategoryShop
_categoryManShop:
    pattern:  /categoryManShop
    defaults: { _controller: ShopProductBundle:AjaxCategoryShop:man }
    
_categoryWomenShop:
    pattern:  /categoryWomenShop
    defaults: { _controller: ShopProductBundle:AjaxCategoryShop:women }

# for class AjaxSubcategoryShop
_subcategoryAccessoriesShop:
    pattern:  /subcategoryAccessoriesShop
    defaults: { _controller: ShopProductBundle:AjaxSubcategoryShop:accessories }
    
_subcategoryBootsShop:
    pattern:  /subcategoryBootsShop
    defaults: { _controller: ShopProductBundle:AjaxSubcategoryShop:boots }

# for class Products
_allProductsCategoryShop:
    pattern:  /{shopname}/allProduct/{idFloor}/{idCategory}
    defaults: { _controller: ShopProductBundle:Products:allProductsCategory }
    
_allProductsSubcategoryShop:
    pattern:  /{shopname}/allProduct/{idFloor}/{idCategory}/{idSubcategory}
    defaults: { _controller: ShopProductBundle:Products:allProductsSubcategory }
    
_productShop:
    pattern:  /{shopname}/allProduct/{idProduct}
    defaults: { _controller: ShopProductBundle:Products:product }