# for class Products
_allProductsShop:
    pattern:  /{shopname}/products/{tags}
    defaults: { _controller: ShopProductBundle:Products:tagsProduct }
    
_productShop:
    pattern:  /{shopname}/product/{id}
    defaults: { _controller: ShopProductBundle:Products:product }

# route for controller Ajax
_addLikeProduct:
    pattern:  /addLikeProduct/{id}
    defaults: { _controller: ShopProductBundle:Ajax:like, _format: json }
    requirements:
        _method: GET

_hashTags:
    pattern:  /hashTags
    defaults: { _controller: ShopProductBundle:Ajax:hashTags, _format: json }
    requirements:
        _method: GET

# route for class Put
_addProduct:
    pattern:  /{shopname}/addProducts
    defaults: { _controller: ShopProductBundle:Put:add }

_updateProduct:
    pattern:  /{shopname}/updateProducts/{id}
    defaults: { _controller: ShopProductBundle:Put:update }
