parameters:
    addNews.class: Shop\NewsBundle\Services\AddNews
    newsXML.class: Shop\NewsBundle\Services\NewsXML

services:
    newsXML:
        class: %newsXML.class%
    
    addNews:
        class: %addNews.class%
        arguments: [ @form.factory, @newsXML ]
