User\UserBundle\Entity\City:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [city]
        name:
            expose: true
            groups: [city]