#route for class ProductsPlatform
_productsPlatform:
    pattern:  /allProducts
    defaults: { _controller: PlatformProductsBundle:ProductsPlatform:all }
    
_productsCategoryPlatform:
    pattern:  /allProductsCategory/{idFloor}/{idCategory}
    defaults: { _controller: PlatformProductsBundle:ProductsPlatform:category }
    
_productsSubcategoryPlatform:
    pattern:  /allProductsSubcategory/{idFloor}/{idCategory}/{idSubcategory}
    defaults: { _controller: PlatformProductsBundle:ProductsPlatform:subcategory }
    
_productPlatform:
    pattern:  /product/{idFloor}/{idCategory}/{idSubcategory}/{id}
    defaults: { _controller: PlatformProductsBundle:ProductsPlatform:product }
    
# route for controller AjaxCategory
_allCategoryMan:
    pattern:  /allCategoryMan
    defaults: { _controller: PlatformProductsBundle:AjaxCategory:man }
    
_allCategoryWomen:
    pattern:  /allCategoryWomen
    defaults: { _controller: PlatformProductsBundle:AjaxCategory:women }

_allCategoryAccessories:
    pattern:  /allCategoryAccessories
    defaults: { _controller: PlatformProductsBundle:AjaxCategory:accessories }
    
_allCategoryBoots:
    pattern:  /allCategoryBoots
    defaults: { _controller: PlatformProductsBundle:AjaxCategory:boots }
