# route for controller AjaxProductLike
_addLikeProduct:
    pattern:  /addLikeProduct
    defaults: { _controller: ShopAddProductsBundle:AjaxProductLike:addLike }
    
# route for class InsertProduct
_addProduct:
    pattern:  /{shopname}/addProducts
    defaults: { _controller: ShopAddProductsBundle:Put:add }

_updateProduct:
    pattern:  /{shopname}/updateProducts/{id}
    defaults: { _controller: ShopAddProductsBundle:Put:update }

    
# route for class ProductImage
_formUploadImage:
    pattern:  /{shopname}/addProducts/formUpload
    defaults: { _controller: ShopAddProductsBundle:ProductImage:form }
    
_uploadImage:
    pattern:  /{shopname}/addProducts/uploadImage
    defaults: { _controller: ShopAddProductsBundle:ProductImage:upload }
    
_images:
    pattern:  /addProducts/images
    defaults: { _controller: ShopAddProductsBundle:ProductImage:images }
    
_imagesDelete:
    pattern: /addProducts/imagesDelete
    defaults: { _controller: ShopAddProductsBundle:ProductImage:delete }
    