# route for controller AjaxProductLike
_addLikeProduct:
    pattern:  /addLikeProduct
    defaults: { _controller: ShopAddProductsBundle:Ajax:like, _format: json }
    requirements:
        _method: GET

_hashTags:
    pattern:  /hashTags
    defaults: { _controller: ShopAddProductsBundle:Ajax:hashTags, _format: json }
    requirements:
        _method: GET
    
# route for class Put
_addProduct:
    pattern:  /{shopname}/addProducts
    defaults: { _controller: ShopAddProductsBundle:Put:add }

_updateProduct:
    pattern:  /{shopname}/updateProducts/{id}
    defaults: { _controller: ShopAddProductsBundle:Put:update }

    
# route for class ProductImage
_uploadImage:
    pattern:  /{shopname}/addProducts/uploadImage
    defaults: { _controller: ShopAddProductsBundle:ProductImage:upload }
    
_imagesDelete:
    pattern: /addProducts/imagesDelete
    defaults: { _controller: ShopAddProductsBundle:ProductImage:delete }
    