# for class CreateShop
_createForm:
    pattern:  /manager/createShop/createForm
    defaults: { _controller: ShopCreateBundle:CreateShop:createForm }

_createShop:
    pattern:  /manager/createShop/createShop
    defaults: { _controller: ShopCreateBundle:CreateShop:createShop }

# for class UpdateShop
_updateForm:
    pattern:  /manager/updateForm/{nameShop}
    defaults: { _controller: ShopCreateBundle:UpdateShop:updateForm }

_updateShop:
    pattern:  /manager/updateShop/{nameShop}
    defaults: { _controller: ShopCreateBundle:UpdateShop:updateShop }

# for class PreviewShop
_previewShop:
    pattern:  /manager/shop/preview/{nameShop}
    defaults: { _controller: ShopCreateBundle:PreviewShop:preview }
    
_formPreview:
    pattern:  /manager/shop/previewForm/{nameShop}
    defaults: { _controller: ShopCreateBundle:PreviewShop:form }
    
_savePreview:
    pattern:  /manager/shop/previewSave
    defaults: { _controller: ShopCreateBundle:PreviewShop:save }
    
# for class Delivery
_delivery: 
    pattern:  /manager/shop/delivery/{nameShop}
    defaults: { _controller: ShopCreateBundle:Delivery:all }
  
_formDelivery:
    pattern:  /manager/shop/deliveryForm
    defaults: { _controller: ShopCreateBundle:Delivery:form }
    
_saveDelivery:
    pattern:  /manager/shop/deliverySave
    defaults: { _controller: ShopCreateBundle:Delivery:save }
    
# for class AjaxCreateShop
_uniqueName:
    pattern:  /manager/createShop/uniqueName
    defaults: { _controller: ShopCreateBundle:AjaxCreateShop:uniqueName }
    
_addLogo:
    pattern:  /manager/createShop/addLogo/{nameShop}
    defaults: { _controller: ShopCreateBundle:AjaxCreateShop:addLogo }