# for class Shop
_createShop:
    pattern:  /manager/createShop
    defaults: { _controller: ShopCreateBundle:Put:add }

_updateShop:
    pattern:  /manager/updateShop/{shopname}
    defaults: { _controller: ShopCreateBundle:Put:update }

_previewShop:
    pattern:  /manager/shop/preview/{shopname}
    defaults: { _controller: ShopCreateBundle:Put:preview }

_delivery:
    pattern:  /manager/shop/delivery/{shopname}
    defaults: { _controller: ShopCreateBundle:Put:delivery }
    
# for class AjaxCreateShop
_uniqueName:
    pattern:  /manager/createShop/uniqueName
    defaults: { _controller: ShopCreateBundle:Ajax:uniqueName, _format: json }
    requirements:
        _method: GET

_addLogo:
    pattern:  /manager/createShop/addLogo/{shopname}
    defaults: { _controller: ShopCreateBundle:Ajax:addLogo, _format: json }
    requirements:
        _method: POST

_saveDescription:
    pattern:  /manager/createShop/description/{shopname}
    defaults: { _controller: ShopCreateBundle:Ajax:description, _format: json }
    requirements:
        _method: POST