# for class Shop
_createShop:
    pattern:  /manager/createShop
    defaults: { _controller: ShopCreateBundle:Shop:add }

_updateShop:
    pattern:  /manager/updateShop/{shopname}
    defaults: { _controller: ShopCreateBundle:Shop:update }

# for class PreviewShop
_previewShop:
    pattern:  /manager/shop/preview/{shopname}
    defaults: { _controller: ShopCreateBundle:PreviewShop:preview }
    
_savePreview:
    pattern:  /manager/shop/previewSave
    defaults: { _controller: ShopCreateBundle:PreviewShop:save }
    
# for class Delivery
_delivery: 
    pattern:  /manager/shop/delivery/{shopname}
    defaults: { _controller: ShopCreateBundle:Delivery:all }
  
_formDelivery:
    pattern:  /manager/shop/deliveryForm
    defaults: { _controller: ShopCreateBundle:Delivery:form }
    
_saveDelivery:
    pattern:  /manager/shop/deliverySave
    defaults: { _controller: ShopCreateBundle:Delivery:save }
    
# for class AjaxCreateShop
_uniqueName:
    pattern:  /manager/createShop/uniqueName
    defaults: { _controller: ShopCreateBundle:AjaxCreateShop:uniqueName }
    
_addLogo:
    pattern:  /manager/createShop/addLogo/{shopname}
    defaults: { _controller: ShopCreateBundle:AjaxCreateShop:addLogo }

# for class Shop
_mainShop:
    pattern:  /{shopname}
    defaults: { _controller: ShopCreateBundle:Main:index }