parameters:

services:
    delivery.id.type.issue_selector:
        class: Shop\CreateBundle\Form\Type\DeliveryIdType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: deliveryId }
