parameters:

services:
    app.type.delivery_selector:
        class: Shop\CreateBundle\Form\Type\DeliveryIdType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: delivery }

    app.type.shopname_selector:
        class: Shop\CreateBundle\Form\Type\ShopnameType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: shopname }