# route for ManagerPartners
_partners:
    pattern:  /manager/partners
    defaults: { _controller: ManagerPartnersBundle:ManagerPartners:partners }
    
_shopPartners:
    pattern:  /manager/partners/shop/{shopname}
    defaults: { _controller: ManagerPartnersBundle:ManagerPartners:shopPartners }
    
_myApplication:
    pattern:  /manager/partners/myApplication
    defaults: { _controller: ManagerPartnersBundle:ManagerPartners:myApplication }
    
_application:
    pattern:  /manager/partners/application
    defaults: { _controller: ManagerPartnersBundle:ManagerPartners:application }
    
# Ajax route for AddPartners    
_addPartner:
    pattern:  /manager/addPartners
    defaults: { _controller: ManagerPartnersBundle:AddPartners:addPartners } 
    
_checkPartner:
    pattern:  /manager/addPartners/checkPartners
    defaults: { _controller: ManagerPartnersBundle:AddPartners:checkPartners }
    
_addListMyShops:
    pattern:  /manager/addPartners/listMyShops
    defaults: { _controller: ManagerPartnersBundle:AddPartners:listMyShops } 
    
_deletePartners:
    pattern:  /manager/addPartners/deletePartners
    defaults: { _controller: ManagerPartnersBundle:AddPartners:delete } 
