parameters:
    deletePartners.class: Manager\PartnersBundle\Services\DeletePartners
    addPartners.class: Manager\PartnersBundle\Services\AddPartners
    checkPartners.class: Manager\PartnersBundle\Services\CheckPartners

services:        
    addPartners:
        class: %addPartners.class%
        arguments: [ @doctrine.orm.entity_manager ]
        
    checkPartners:
        class: %checkPartners.class%
        arguments: [ @doctrine.orm.entity_manager ]
        
    deletePartners:
        class: %deletePartners.class%
        arguments: [ @doctrine.orm.entity_manager ]
