# route for UserFriends
_friends:
    pattern:  /firends
    defaults: { _controller: UserFriendsBundle:Friends:friends }

_searchUsers:
    pattern:  /friends/search
    defaults: { _controller: UserFriendsBundle:Friends:search }

_userFriends:
    pattern:  /firends/user/{id}
    defaults: { _controller: UserFriendsBundle:Friends:userFriends }
    
_myApplicationFriends:
    pattern:  /firends/myApplication
    defaults: { _controller: UserFriendsBundle:Friends:myApplication }
    
_applicationFriends:
    pattern:  /firends/application
    defaults: { _controller: UserFriendsBundle:Friends:application }
    
# Ajax route for AddFriends
_addFriends:
    pattern:  /friends/add/{id}
    defaults: { _controller: UserFriendsBundle:Ajax:add, _format: json }
    methods: [GET]
    
_checkFriends:
    pattern:  /friends/add/check/{type}/{user}
    defaults: { _controller: UserFriendsBundle:Ajax:check, _format: json }
    methods: [GET]
    
_addListMyFriends:
    pattern:  /friends/add/list/{id}
    defaults: { _controller: UserFriendsBundle:Ajax:list, _format: json }
    methods: [GET]
    
_deleteFriends:
    pattern:  /friends/remove/{id}
    defaults: { _controller: UserFriendsBundle:Ajax:remove, _format: json }
    methods: [GET]

_resultSearch:
    pattern:  /friends/result/search
    defaults: { _controller: UserFriendsBundle:Ajax:search, _format: json }
    methods: [GET|POST]