# for class Shop
_mainShop:
    pattern:  /{shopname}
    defaults: { _controller: ShopInformationBundle:Main:index }

# for class ShopInformation
_shopInformation:
    pattern: /{shopname}/shopInformation
    defaults: { _controller: ShopInformationBundle:ShopInformation:shop }
    
_ajaxShop:
    pattern: /{shopname}/ajaxShop
    defaults: { _controller: ShopInformationBundle:ShopInformation:ajaxShop }
    
_partnersShop:
    pattern: /{shopname}/partnersShop
    defaults: { _controller: ShopInformationBundle:ShopInformation:partnersShop }
    
_deliveryShop:
    pattern: /{shopname}/deliveryShop
    defaults: { _controller: ShopInformationBundle:ShopInformation:deliveryShop }
    
_paymentShop:
    pattern: /{shopname}/paymentShop
    defaults: { _controller: ShopInformationBundle:ShopInformation:paymentShop }
    
#for class ShopComments
_commentsShop:
    pattern: /{shopname}/commentsShop
    defaults: { _controller: ShopInformationBundle:ShopComments:formComments }
    
_addCommentsShop:
    pattern: /addCommentsShop
    defaults: { _controller: ShopInformationBundle:ShopComments:addComments }
    
# for class AjaxShopLike
_addLikeShop:
    pattern: /addLikeShop
    defaults: { _controller: ShopInformationBundle:AjaxShopLike:addLike }
