# routes for class UserInformationController
_property:
    pattern:  /property
    defaults: { _controller: UserPropertyBundle:UserInformation:property }
        
_formInformation:
    pattern:  /property/formInformation
    defaults: { _controller: UserPropertyBundle:UserInformation:formInformation }

_addInformation:
    pattern:  /property/addInformation
    defaults: { _controller: UserPropertyBundle:UserInformation:addInformation }
    
# routes for class PreviewUserController
_formPreviewInformation:
    pattern:  /property/formPreviewInformation
    defaults: { _controller: UserPropertyBundle:PreviewUser:form }
    
_addPreviewInformation:
    pattern:  /property/addPreviewInformation
    defaults: { _controller: UserPropertyBundle:PreviewUser:save }
    
_addPreviewUpload:
    pattern:  /property/uploadAvatar
    defaults: { _controller: UserPropertyBundle:PreviewUser:upload }
    
# rotes for class ChangePasswordController
_formPassword:
    pattern:  /property/formPassword
    defaults: { _controller: UserPropertyBundle:ChangePassword:formPassword }
    
_changePassword:
    pattern:  /property/changePassword
    defaults: { _controller: UserPropertyBundle:ChangePassword:changePassword }
    
# route for class AjaxCity
_city:
    pattern:  /city
    defaults: { _controller: UserPropertyBundle:AjaxProperty:city }
    
_emailProperty:
    pattern:  /emailProperty
    defaults: { _controller: UserPropertyBundle:AjaxProperty:email }
