# routes for class UserInformationController
_property:
    pattern:  /property
    defaults: { _controller: UserPropertyBundle:UserInformation:property }
        
_formInformation:
    pattern:  /property/information
    defaults: { _controller: UserPropertyBundle:UserInformation:formInformation }

_formPassword:
    pattern:  /property/password
    defaults: { _controller: UserPropertyBundle:UserInformation:formPassword }
    
# routes for class PreviewUserController
_formPreviewInformation:
    pattern:  /property/formPreviewInformation
    defaults: { _controller: UserPropertyBundle:PreviewUser:form }
    
_addPreviewInformation:
    pattern:  /property/addPreviewInformation
    defaults: { _controller: UserPropertyBundle:PreviewUser:save }
    
_addPreviewUpload:
    pattern:  /property/uploadAvatar
    defaults: { _controller: UserPropertyBundle:PreviewUser:upload }
    
# route for class AjaxCity
_city:
    pattern:  /city
    defaults: { _controller: UserPropertyBundle:AjaxProperty:city }
    
_emailProperty:
    pattern:  /emailProperty
    defaults: { _controller: UserPropertyBundle:AjaxProperty:email }
