parameters:
    formUserInformation.class: User\PropertyBundle\Services\FormUserInformation
    formPreviewUser.class: User\PropertyBundle\Services\FormPreviewUser
    formUploadAvatar.class: User\PropertyBundle\Services\FormUploadAvatar
    savePreviewXML.class: User\PropertyBundle\Services\SavePreviewXML
    changePassword.class: User\PropertyBundle\Services\ChangePassword

services:       
    formUserInformation:
        class: %formUserInformation.class%
        arguments: [ @form.factory, @doctrine.orm.entity_manager ]
        
    formPreviewUser:
        class: %formPreviewUser.class%
        arguments: [ @form.factory, @savePreviewXML ]
        
    formUploadAvatar:
        class: %formUploadAvatar.class%
        arguments: [ @doctrine.orm.entity_manager, @form.factory ]
        
    savePreviewXML:
        class: %savePreviewXML.class%
        
    changePassword:
        class: %changePassword.class%
        arguments: [ @doctrine.orm.entity_manager, @form.factory, @hashPassword ]