parameters:
    deletePartners.class: User\PartnersBundle\Services\DeletePartners
    addPartners.class: User\PartnersBundle\Services\AddPartners
    checkPartners.class: User\PartnersBundle\Services\CheckPartners
    searchPartners.class: User\PartnersBundle\Services\SearchPartners

services:        
    addPartners:
        class: %addPartners.class%
        arguments: [ @doctrine.orm.entity_manager ]
        
    checkPartners:
        class: %checkPartners.class%
        arguments: [ @doctrine.orm.entity_manager ]
        
    deletePartners:
        class: %deletePartners.class%
        arguments: [ @doctrine.orm.entity_manager ]

    searchPartners:
        class: %searchPartners.class%
        arguments: [ @doctrine.orm.entity_manager, @form.factory ]