parameters:
    createAdvertisingShop.class: Manager\AdvertisingBundle\Services\CreateAdvertisingShop
    createPlatforn.class: Manager\AdvertisingBundle\Services\CreatePlatforn
    advertisingManager.class: Manager\AdvertisingBundle\Services\AdvertisingManager
    advertising.class: Manager\AdvertisingBundle\Services\Advertising
    
services:
    advertising:
        class: %advertising.class%
        
    advertisingManager:
        class: %advertisingManager.class%
        arguments: [ @doctrine.orm.entity_manager ]
        
    createAdvertisingShop:
        class: %createAdvertisingShop.class%
        arguments: [ @doctrine.orm.entity_manager, @form.factory ]
        
    createPlatforn:
        class: %createPlatforn.class%
        arguments: [ @doctrine.orm.entity_manager, @form.factory ]
