services:
    advertising.form.type.advertising_platform:
        class: User\AdvertisingBundle\Form\Type\AdvertisingPlatformType
        arguments: ["@security.token_storage"]
        tags:
            - { name: form.type }

    advertising.form.type.advertising_shop:
        class: User\AdvertisingBundle\Form\Type\AdvertisingShopType
        arguments: ["@security.token_storage"]
        tags:
            - { name: form.type }